export const moduleCards = [
  {
    alias: 'pgkm',
    shortAlias: 'pgkm',
    name: 'Package Managers',
    path: 'src/core/pgkm',
    components: [
      'bun',
      'cargo',
      'choco',
      'chocolatey',
      'composer',
      'conda',
      'dotnet-tool',
      'gem',
      'go',
      'mamba',
      'nodejs',
      'npm',
      'nuget',
      'nvm',
      'pip',
      'pipx',
      'pnpm',
      'scoop',
      'vcpkg',
      'winget',
      'yarn',
    ],
  },
  {
    alias: 'web-development',
    shortAlias: 'wdev',
    name: 'Web Development',
    path: 'src/core/wdev',
    components: ['angular-tools', 'browsers', 'nodejs', 'react-tools', 'vite', 'vue-tools', 'yarn'],
  },
  {
    alias: 'ai-development-tools',
    shortAlias: 'aidve',
    name: 'AI Development',
    path: 'src/core/aidve',
    components: [
      'aws-cli',
      'azure-cli',
      'codex-cli',
      'gcloud-cli',
      'grok-cli',
      'netlify-cli',
      'node',
      'python',
      'redis',
      'vercel-cli',
      'xampp',
    ],
  },
  {
    alias: 'mobile-development',
    shortAlias: 'mdev',
    name: 'Mobile Development',
    path: 'src/core/mdev',
    components: ['android-studio', 'flutter', 'react-native-cli'],
  },
  {
    alias: 'wsl-linux',
    shortAlias: 'wsl',
    name: 'WSL Linux',
    path: 'src/core/wsl',
    components: ['docker-desktop', 'ubuntu', 'wsl'],
  },
  {
    alias: 'cloud-development',
    shortAlias: 'cdev',
    name: 'Cloud Development',
    path: 'src/core/cdev',
    components: ['aws-cli', 'azure-cli', 'gcloud-cli', 'kubectl', 'terraform'],
  },
  {
    alias: 'common-development',
    shortAlias: 'codev',
    name: 'Common Development',
    path: 'src/core/codev',
    components: [
      '7zip',
      'brave',
      'chrome',
      'firefox',
      'gh',
      'git',
      'github-desktop',
      'jdk',
      'powershell',
      'powertoys',
      'telegram',
      'vscode',
      'whatsapp',
      'windows-terminal',
    ],
  },
  { alias: 'devops', shortAlias: 'devops', name: 'DevOps', path: 'src/core/devops', components: ['ansible', 'jenkins', 'terraform'] },
  { alias: 'data-science', shortAlias: 'dscience', name: 'Data Science', path: 'src/core/dscience', components: ['jupyter', 'pandas', 'pytorch', 'tensorflow'] },
]

export const quickCommands = [
  'Set-ExecutionPolicy Bypass -Scope Process -Force; iwr https://raw.githubusercontent.com/anshulyadav-git/setupx-windows-setup/main/install.ps1 | iex',
  'stx pgkm',
  'stx install web-development  # alias: stx wdev',
  'stx install ai-development-tools  # alias: stx aidve',
  'stx install mobile-development  # alias: stx mdev',
  'stx install wsl-linux  # alias: stx wsl',
  'stx install cloud-development  # alias: stx cdev',
  'stx install common-development  # alias: stx codev',
  'stx install devops',
  'stx install data-science  # alias: stx dscience',
]

export const installOneLiner =
  'Set-ExecutionPolicy Bypass -Scope Process -Force; iwr https://raw.githubusercontent.com/anshulyadav-git/setupx-windows-setup/main/install.ps1 | iex'


